version: '3'
services:
  parser:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./main.py:/app/maim.py
    environment:
      - MONGO_URI=mongodb://cnwv:Dasdas123@91.203.192.16:27017/baza
    depends_on:
      - mongodb
    networks:
      - app_network
  mongodb:
    image: mongo:4.4
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
