version: '3'
services:
  parser:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    command: mongod --bind_ip_all --auth
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
volumes:
  mongodb-data:
